### ISSUE TITLE
Configure gqlgen steps not working / not correct

### ISSUE THREAD

**Issue by codenakama** [prisma/prisma-content-feedback#40]
**Article Title (if relevant)**
Build an App

**Describe the content issue**
Tutorial describes a step that relies on values that have not been created/defined beforehand and build fails.
On the "Now add the following configuration to it:" under the "Configure gqlgen" section it says to paste:
```
schema: server/schema.graphql
exec:
  filename: server/generated.go
models:
  Post:
    model: hello-world/prisma-client.Post
  User:
    model: hello-world/prisma-client.User
resolver:
  # Goal: copy&paste from generated file
  filename: tmp/resolver.go
  type: Resolver
```
but models section is not valid.

**Describe the solution you'd like to see**
I don't know what's the solution.

**Additional context**
console output after running `go run scripts/gqlgen.go`
```
test-prisma-go go run scripts/gqlgen.go
exec plan failed: unable to resolve package for test-prisma-go/prisma-client.User: cannot find package "test-prisma-go/prisma-client" in any of:
        /Users/ricardoabreu/Development/go/src/github.com/test-prisma-go/vendor/test-prisma-go/prisma-client (vendor tree)
        /usr/local/Cellar/go/1.10.3/libexec/src/test-prisma-go/prisma-client (from $GOROOT)
        /Users/ricardoabreu/Development/go/src/test-prisma-go/prisma-client (from $GOPATH)

exit status 2
```
